import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';
import './globals.css';
// import RootLayout from './rootLayout';

const RootLayout = dynamic(
  () => {
    return import('./rootLayout');
  },
  { ssr: false }
);

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: '财务管理系统',
  description: 'Generated by create next app'
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
